version: '3'

services:
  api:
    container_name: api
    build: ./
    ports:
      - '3000:3000'
    command: ./gin-api
  db:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'go'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3006'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: